"""Add note column to mood table

Revision ID: 82151094965f
Revises: 
Create Date: 2025-04-16 15:31:37.356476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82151094965f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
